name: Build/release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Electron app
        run: |
          npm install
          npm run make

      - name: Publish release
        uses: softprops/action-gh-release@v1
